<?php
require __DIR__.'/oyunchu_config.php';
$msg=''; $err='';
$defaults=[
'sualduellosu'=>['Sual Duellosu','⚔️','#c8506a','es_duello_players','score'],
'teletime'=>['Tele Time','📺','#3498db','tt_scores','score'],
'zencir'=>['Zəncir','⛓️','#e67e22','zc_scores','score'],
'milyoncu'=>['Milyonçu','💰','#c9a84c','mc_scores','prize'],
'suretturu'=>['Sürət Turu','⚡','#e94560','sr_scores','score'],
'sozutap'=>['Sözü Tap','🔤','#16a085','sz_results','score'],
'kelmezencir'=>['Kəlmə Zənciri','🔗','#9b59b6','kz_scores','score'],
'sudoku'=>['Sudoku','🔢','#2980b9','su_scores','score'],
'sozyagishi'=>['Sürətli Söz Yağışı','🌧️','#00b4d8','sy_scores','score'],
'sahmat'=>['Şahmat','♞','#5d4037',null,null],
'domino'=>['Domino','🁫','#3498db','domino_scores','score'],
];
function sync_games(){global $conn,$defaults;$root=dirname(__DIR__,2).'/games';$dirs=[];if(is_dir($root)){foreach(scandir($root) as $d){if($d==='.'||$d==='..'||$d==='oyunchu'||!is_dir($root.'/'.$d)||!is_file($root.'/'.$d.'/config.php'))continue;$dirs[]=$d;}}
foreach($dirs as $slug){$q=$conn->prepare('SELECT id FROM oh_games WHERE slug=?');$q->bind_param('s',$slug);$q->execute();if($q->get_result()->fetch_assoc())continue;$d=$defaults[$slug]??[ucwords(str_replace(['-','_'],' ',$slug)),'🎮','#999999',null,null];$nk=$slug.'_name';$lk=$slug.'_logo';$path='/games/'.$slug;$ins=$conn->prepare('INSERT INTO oh_games(slug,path,name_key,logo_key,default_name,default_logo,color,score_table,score_col,sort_order,is_active) VALUES(?,?,?,?,?,?,?,?,?,?,1)');$sort=100;$ins->bind_param('sssssssssi',$slug,$path,$nk,$lk,$d[0],$d[1],$d[2],$d[3],$d[4],$sort);$ins->execute();}
}
sync_games();
if($_SERVER['REQUEST_METHOD']==='POST'){ga_verify();$action=$_POST['action']??'';if($action==='save'){$id=(int)$_POST['id'];$name=trim($_POST['default_name']??'');$logo=trim($_POST['default_logo']??'🎮');$color=trim($_POST['color']??'#999999');$sort=(int)($_POST['sort_order']??0);$active=!empty($_POST['is_active'])?1:0;if($id&&$name!==''){$q=$conn->prepare('UPDATE oh_games SET default_name=?,default_logo=?,color=?,sort_order=?,is_active=? WHERE id=?');$q->bind_param('sssiii',$name,$logo,$color,$sort,$active,$id);$q->execute();$msg='Oyun yadda saxlanıldı.';ga_audit('oyunchu_all_game_save','oh_games',$id,$name);}}elseif($action==='sync'){sync_games();$msg='Arxivdəki oyunlar yenidən yoxlanıldı və çatışmayanlar əlavə edildi.';ga_audit('oyunchu_games_sync','oh_games',null,'Filesystem sync');}}
$rows=$conn->query('SELECT * FROM oh_games ORDER BY sort_order,id')->fetch_all(MYSQLI_ASSOC);
?><!doctype html><html lang="az" data-theme="dark"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Bütün oyunlar</title><script>document.documentElement.setAttribute('data-theme',localStorage.getItem('esevgili_theme')||'dark');</script></head><body><?php include __DIR__.'/oyunchu_sidebar.php';?><main class="ga-main"><div class="ga-top"><b>🎮 Bütün oyunların idarəsi</b><form method="post" style="margin:0"><?=csrf_field()?><input type="hidden" name="action" value="sync"><button class="ga-btn ga-primary">Arxivlə sinxronlaşdır</button></form></div><div class="ga-content"><?php if($msg):?><div class="ga-alert">✅ <?=ga_h($msg)?></div><?php endif;?><div class="ga-card"><p class="ga-muted">Bu siyahı <b>games/</b> arxivindəki bütün oyunları və <b>oh_games</b> qeydiyyatını bir yerdə idarə edir. Ad, loqo, rəng, sıra və aktivlik burada dəyişir.</p></div><br><?php foreach($rows as $r):?><div class="ga-card" style="margin-bottom:14px"><form method="post" class="ga-form"><?=csrf_field()?><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?=$r['id']?>"><div><label class="ga-label">Oyun</label><div style="font-size:18px;font-weight:800"><?=ga_h($r['default_logo'].' '.$r['default_name'])?></div><div class="ga-muted">slug: <?=ga_h($r['slug'])?></div></div><div><label class="ga-label">Görüntü adı</label><input class="ga-input" name="default_name" value="<?=ga_h($r['default_name'])?>"></div><div><label class="ga-label">Loqo / emoji</label><input class="ga-input" name="default_logo" value="<?=ga_h($r['default_logo'])?>"></div><div><label class="ga-label">Rəng</label><input class="ga-input" name="color" value="<?=ga_h($r['color'])?>"></div><div><label class="ga-label">Sıra</label><input class="ga-input" type="number" name="sort_order" value="<?=$r['sort_order']?>"></div><div style="padding-top:24px"><label><input type="checkbox" name="is_active" <?=$r['is_active']?'checked':''?>> Aktiv</label></div><div class="full"><button class="ga-btn ga-primary">Yadda saxla</button> <a class="ga-btn ga-mutedbtn" href="oyunchu_game_settings.php?game=<?=urlencode($r['slug'])?>">Parametrlər</a> <a class="ga-btn ga-mutedbtn" href="oyunchu_game_questions.php?game=<?=urlencode($r['slug'])?>">Sual/kartlar</a> <a class="ga-btn ga-mutedbtn" href="<?=ga_h($r['path'])?>" target="_blank">Oyunu aç</a></div></form></div><?php endforeach;?></div></main></body></html>
