<?php require __DIR__.'/oyunchu_config.php'; $msg='';
if($_SERVER['REQUEST_METHOD']==='POST'){ga_verify();$a=$_POST['action']??'';try{
 if($a==='premium'){ $id=(int)$_POST['id'];$status=$_POST['status'];if(!in_array($status,['pending','approved','rejected'],true))throw new Exception('Status');$q=$conn->prepare('UPDATE oh_premium_requests SET status=? WHERE id=?');$q->bind_param('si',$status,$id);$q->execute();if($status==='approved'){ $r=$conn->query("SELECT user_id FROM oh_premium_requests WHERE id=".$id)->fetch_assoc(); if($r){$uid=(int)$r['user_id'];$conn->query("UPDATE users SET vip_level=1 WHERE id=$uid");}}ga_audit('oyunchu_premium',$id,$status);$msg='Premium sorğusu yeniləndi.';
 } elseif($a==='ref_reward'){ $id=(int)$_POST['id'];$r=$conn->query("SELECT referrer_id,referred_id,rewarded FROM oh_referral_log WHERE id=$id")->fetch_assoc();if($r&&!$r['rewarded']){$ref=(int)$r['referrer_id'];$conn->query("UPDATE oh_referral_log SET rewarded=1 WHERE id=$id");$reward=20; try{$st=$conn->prepare("SELECT svalue FROM es_settings WHERE skey='oh_referral_reward' LIMIT 1");$st->execute();$rv=$st->get_result()->fetch_column();if($rv!==null&&$rv!=='')$reward=max(0,(int)$rv);}catch(Throwable $e){} $q=$conn->prepare("UPDATE users SET streak_coins=streak_coins+? WHERE id=?");$q->bind_param('ii',$reward,$ref);$q->execute();$msg='Referral mükafatı verildi.';ga_audit('oyunchu_referral_reward','oh_referral_log',$id,$reward.' coin');}}
}catch(Throwable $e){$msg='Xəta: '.$e->getMessage();}}
$tab=$_GET['tab']??'premium'; $refReward=20; try{$st=$conn->query("SELECT svalue FROM es_settings WHERE skey='oh_referral_reward' LIMIT 1");$v=$st->fetch_column();if($v!==null&&$v!=='')$refReward=max(0,(int)$v);}catch(Throwable $e){}
$premium=$conn->query("SELECT r.*,u.name,u.email,u.username FROM oh_premium_requests r LEFT JOIN users u ON u.id=r.user_id ORDER BY FIELD(r.status,'pending','approved','rejected'),r.id DESC LIMIT 100")->fetch_all(MYSQLI_ASSOC);
$refs=$conn->query("SELECT r.*,u1.name referrer_name,u2.name referred_name FROM oh_referral_log r LEFT JOIN users u1 ON u1.id=r.referrer_id LEFT JOIN users u2 ON u2.id=r.referred_id ORDER BY r.id DESC LIMIT 100")->fetch_all(MYSQLI_ASSOC);
$daily=$conn->query("SELECT d.*,u.name FROM oh_daily_login d LEFT JOIN users u ON u.id=d.user_id ORDER BY d.total_claims DESC LIMIT 100")->fetch_all(MYSQLI_ASSOC);
$push=$conn->query("SELECT p.*,u.name FROM oh_push_subscriptions p LEFT JOIN users u ON u.id=p.user_id ORDER BY p.id DESC LIMIT 100")->fetch_all(MYSQLI_ASSOC);
$ads=$conn->query("SELECT a.*,u.name FROM oh_ad_rewards a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.id DESC LIMIT 100")->fetch_all(MYSQLI_ASSOC);
$ch=$conn->query("SELECT c.*,u.name FROM oh_challenges c LEFT JOIN users u ON u.id=c.challenger_id ORDER BY c.id DESC LIMIT 100")->fetch_all(MYSQLI_ASSOC);
$claims=$conn->query("SELECT q.*,u.name FROM oh_quest_claims q LEFT JOIN users u ON u.id=q.user_id ORDER BY q.claim_date DESC LIMIT 100")->fetch_all(MYSQLI_ASSOC);
?><!doctype html><html lang="az" data-theme="dark"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Oyunçu Ekosistemi</title><script>document.documentElement.setAttribute('data-theme',localStorage.getItem('esevgili_theme')||'dark');</script></head><body><?php include __DIR__.'/oyunchu_sidebar.php';?><main class="ga-main"><div class="ga-top"><b>👥 Oyunçu ekosistemi</b></div><div class="ga-content"><?php if($msg):?><div class="ga-alert"><?=ga_h($msg)?></div><?php endif;?><div style="display:flex;gap:7px;flex-wrap:wrap;margin-bottom:15px"><?php foreach(['premium'=>'💎 Premium','ref'=>'🔗 Referral','daily'=>'📅 Daily Login','quest'=>'🎯 Quest','challenge'=>'⚔️ Challenge','push'=>'🔔 Push','ads'=>'📺 Reklam'] as $k=>$v):?><a class="ga-btn <?=($tab===$k?'ga-primary':'ga-mutedbtn')?>" href="?tab=<?=$k?>"><?=ga_h($v)?></a><?php endforeach;?></div><div class="ga-card">
<?php if($tab==='premium'):?><h3>Premium sorğuları</h3><table class="ga-table"><tr><th>İstifadəçi</th><th>Status</th><th>Tarix</th><th></th></tr><?php foreach($premium as $r):?><tr><td><?=ga_h($r['name']??('ID '.$r['user_id']))?></td><td><?=ga_h($r['status'])?></td><td><?=ga_h($r['created_at'])?></td><td><?php if($r['status']==='pending'):?><form method="post" style="display:inline"><?=csrf_field()?><input type="hidden" name="action" value="premium"><input type="hidden" name="id" value="<?=$r['id']?>"><input type="hidden" name="status" value="approved"><button class="ga-btn ga-primary">Təsdiq</button></form> <form method="post" style="display:inline"><?=csrf_field()?><input type="hidden" name="action" value="premium"><input type="hidden" name="id" value="<?=$r['id']?>"><input type="hidden" name="status" value="rejected"><button class="ga-btn ga-danger">Rədd</button></form><?php endif;?></td></tr><?php endforeach;?></table>
<?php elseif($tab==='ref'):?><h3>Referral log</h3><table class="ga-table"><tr><th>Dəvət edən</th><th>Qoşulan</th><th>Reward</th><th>Tarix</th><th></th></tr><?php foreach($refs as $r):?><tr><td><?=ga_h($r['referrer_name']??$r['referrer_id'])?></td><td><?=ga_h($r['referred_name']??$r['referred_id'])?></td><td><?=((int)$r['rewarded'])?'✅':'⏳'?></td><td><?=$r['created_at']?></td><td><?php if(!$r['rewarded']):?><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="ref_reward"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="ga-btn ga-primary"><?=((int)($refReward??20))?> coin ver</button></form><?php endif;?></td></tr><?php endforeach;?></table>
<?php elseif($tab==='daily'):?><h3>Daily Login</h3><table class="ga-table"><tr><th>İstifadəçi</th><th>Streak</th><th>Son claim</th><th>Total</th></tr><?php foreach($daily as $r):?><tr><td><?=ga_h($r['name']??$r['user_id'])?></td><td><?=$r['streak']?></td><td><?=$r['last_claim_date']?></td><td><?=$r['total_claims']?></td></tr><?php endforeach;?></table>
<?php elseif($tab==='quest'):?><h3>Quest claimləri</h3><table class="ga-table"><tr><th>İstifadəçi</th><th>Quest</th><th>Tarix</th></tr><?php foreach($claims as $r):?><tr><td><?=ga_h($r['name']??$r['user_id'])?></td><td><?=ga_h($r['quest_key'])?></td><td><?=$r['claim_date']?></td></tr><?php endforeach;?></table>
<?php elseif($tab==='challenge'):?><h3>Challenge-lər</h3><table class="ga-table"><tr><th>İstifadəçi</th><th>Oyun</th><th>Score</th><th>Tarix</th></tr><?php foreach($ch as $r):?><tr><td><?=ga_h($r['name']??$r['challenger_id'])?></td><td><?=ga_h($r['game_slug'])?></td><td><?=$r['score_to_beat']?></td><td><?=$r['created_at']?></td></tr><?php endforeach;?></table>
<?php elseif($tab==='push'):?><h3>Push abunəlikləri</h3><table class="ga-table"><tr><th>İstifadəçi</th><th>Endpoint</th><th>Tarix</th></tr><?php foreach($push as $r):?><tr><td><?=ga_h($r['name']??$r['user_id'])?></td><td><?=ga_h(substr($r['endpoint'],0,80))?>…</td><td><?=$r['created_at']?></td></tr><?php endforeach;?></table>
<?php else:?><h3>Reklam mükafatları</h3><table class="ga-table"><tr><th>İstifadəçi</th><th>Coin</th><th>Vaxt</th></tr><?php foreach($ads as $r):?><tr><td><?=ga_h($r['name']??$r['user_id'])?></td><td>🪙 <?=$r['coins']?></td><td><?=$r['watched_at']?></td></tr><?php endforeach;?></table><?php endif;?></div></div></main></body></html>
