<?php
require __DIR__.'/oyunchu_config.php';
$msg='';
$games=$conn->query('SELECT * FROM oh_games ORDER BY sort_order,id')->fetch_all(MYSQLI_ASSOC);
$slug=trim($_GET['game']??$_POST['game']??'');
if($_SERVER['REQUEST_METHOD']==='POST'){
 ga_verify(); $slug=trim($_POST['game']??'');
 if($slug!==''){
  $keys=[];foreach($_POST['setting_key']??[] as $i=>$k){$k=trim($k);$v=(string)($_POST['setting_value'][$i]??'');if($k!==''&&preg_match('/^[A-Za-z0-9_.-]{1,100}$/',$k))$keys[$k]=$v;}
  $conn->query("CREATE TABLE IF NOT EXISTS oh_game_settings (game_slug VARCHAR(30) NOT NULL, skey VARCHAR(100) NOT NULL, svalue TEXT NULL, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY(game_slug,skey)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
  $q=$conn->prepare('INSERT INTO oh_game_settings(game_slug,skey,svalue) VALUES(?,?,?) ON DUPLICATE KEY UPDATE svalue=VALUES(svalue)');foreach($keys as $k=>$v){$q->bind_param('sss',$slug,$k,$v);$q->execute();}
  // Name/logo settings also remain compatible with existing games.
  $gq=$conn->prepare('SELECT name_key,logo_key,default_name,default_logo FROM oh_games WHERE slug=?');$gq->bind_param('s',$slug);$gq->execute();$g=$gq->get_result()->fetch_assoc();
  if($g){$conn->query("CREATE TABLE IF NOT EXISTS es_settings(skey VARCHAR(100) PRIMARY KEY,svalue TEXT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");$ss=$conn->prepare('INSERT INTO es_settings(skey,svalue) VALUES(?,?) ON DUPLICATE KEY UPDATE svalue=VALUES(svalue)');$ss->bind_param('ss',$g['name_key'],$g['default_name']);$ss->execute();$ss->bind_param('ss',$g['logo_key'],$g['default_logo']);$ss->execute();}
  $msg='Parametrlər yadda saxlanıldı.';ga_audit('oyunchu_game_settings_dynamic','oh_game_settings',null,$slug);
 }
}
$selected=null;foreach($games as $g)if($g['slug']===$slug){$selected=$g;break;}
$settings=[];if($selected){$conn->query("CREATE TABLE IF NOT EXISTS oh_game_settings (game_slug VARCHAR(30) NOT NULL, skey VARCHAR(100) NOT NULL, svalue TEXT NULL, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY(game_slug,skey)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");$q=$conn->prepare('SELECT skey,svalue FROM oh_game_settings WHERE game_slug=? ORDER BY skey');$q->bind_param('s',$slug);$q->execute();$settings=$q->get_result()->fetch_all(MYSQLI_ASSOC);}
?><!doctype html><html lang="az" data-theme="dark"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Oyun parametrləri</title><script>document.documentElement.setAttribute('data-theme',localStorage.getItem('esevgili_theme')||'dark');</script></head><body><?php include __DIR__.'/oyunchu_sidebar.php';?><main class="ga-main"><div class="ga-top"><b>🎛️ Oyun parametrləri</b></div><div class="ga-content"><?php if($msg):?><div class="ga-alert">✅ <?=ga_h($msg)?></div><?php endif;?><div class="ga-card"><form method="get" class="ga-form"><div><label class="ga-label">Oyun seç</label><select class="ga-input" name="game" onchange="this.form.submit()"><option value="">Seçin...</option><?php foreach($games as $g):?><option value="<?=ga_h($g['slug'])?>" <?=$slug===$g['slug']?'selected':''?>><?=ga_h($g['default_logo'].' '.$g['default_name'])?></option><?php endforeach;?></select></div></form></div><?php if($selected):?><br><form method="post"><div class="ga-card"><h3><?=ga_h($selected['default_logo'].' '.$selected['default_name'])?></h3><p class="ga-muted">Burada oyuna aid əlavə key/value parametrlərini kod dəyişmədən saxlaya bilərsən. Oyun kodu həmin key-i oxuduqda parametr birbaşa tətbiq olunur.</p><?=csrf_field()?><input type="hidden" name="game" value="<?=ga_h($slug)?>"><div id="settings"><?php foreach($settings as $i=>$s):?><div class="ga-form" style="grid-template-columns:1fr 2fr;gap:8px;margin-bottom:8px"><input class="ga-input" name="setting_key[]" value="<?=ga_h($s['skey'])?>" placeholder="setting_key"><input class="ga-input" name="setting_value[]" value="<?=ga_h($s['svalue'])?>" placeholder="dəyər"></div><?php endforeach;?><div class="ga-form" style="grid-template-columns:1fr 2fr;gap:8px"><input class="ga-input" name="setting_key[]" placeholder="yeni_key"><input class="ga-input" name="setting_value[]" placeholder="yeni dəyər"></div></div><button class="ga-btn ga-primary">Yadda saxla</button></div></form><?php endif;?></div></main></body></html>
